integration/multi-export/COMPONENT_INDEX.md
integration/multi-export/types/Quote.d.ts
integration/single-export/types/index.d.ts
package.json
src/ComponentParser.ts
yarn.lock

**Changes**
- upgrade svelte to version 3.30
- refactor `ComponentParser.ts` to use exported svelte compiler walk interface
- upgrade prettier to version 2.2

refactor: bump svelte, prettier dependencies

---

integration/multi-export-typed/COMPONENT_API.json
integration/multi-export-typed/types/Button.d.ts
integration/multi-export-typed/types/Link.d.ts
integration/multi-export-typed/types/Quote.d.ts
integration/multi-export/COMPONENT_API.json
integration/multi-export/types/Button.d.ts
integration/multi-export/types/Link.d.ts
integration/multi-export/types/Quote.d.ts
integration/single-export/COMPONENT_API.json
integration/single-export/test/test.svelte
integration/single-export/types/Button.d.ts
integration/single-export/types/index.d.ts
package.json
src/cli.ts
src/create-exports.ts
src/get-svelte-entry.ts
src/get-svelte-files.ts
src/parse-exports.ts
src/rollup-plugin.ts
src/writer/writer-json.ts
src/writer/writer-ts-definitions.ts
tests/create-exports.test.ts
tests/get-svelte-files.test.ts
tests/integration.js
tests/parse-exports.test.ts
yarn.lock

**Changes**
- use acorn to parse base exports (should address #13 )
- use fast-glob to collect all *.svelte files from the Svelte source folder specified in `package.json#svelte`
- format TS definitions using a prettier printWidth of 80 instead of 120
**Breaking Changes**
- `filePath` in generated JSON output is relative instead of absolute (normalized using `path.normalize`)

Use acorn to parse exports, use fast-glob to obtain Svelte component files from source folder

---

package.json
src/rollup-plugin.ts
yarn.lock

This attempts to address #12 and #24. To avoid errors by the svelte compiler, this will preprocess the code to handle typescript and strip away any style blocks since they are not necessary. 
Initially, I considered passing in an array of preprocessors as one of the sveld options. But that didn't seem right as the end user should not have to know the internal workings of sveld. Keeping all the logic within sveld seems to make more sense.
I would appreciate any feedback or alternative approaches. We have a component library that we'd like to convert to typescript and is dependent on this working. Thanks!

preprocess to ignore styles and handle typescript

---

integration/carbon/COMPONENT_API.json
integration/glob/COMPONENT_API.json
integration/multi-export-typed/COMPONENT_API.json
integration/multi-export/COMPONENT_API.json
integration/single-export/COMPONENT_API.json
src/ComponentParser.ts
src/writer/writer-ts-definitions.ts
tests/snapshots/bind-this-multiple/output.json
tests/snapshots/bind-this/output.json
tests/snapshots/function-declaration/input.svelte
tests/snapshots/function-declaration/output.d.ts
tests/snapshots/function-declaration/output.json
tests/snapshots/infer-basic/output.d.ts
tests/snapshots/infer-basic/output.json
tests/snapshots/infer-with-types/output.d.ts
tests/snapshots/infer-with-types/output.json
tests/snapshots/rest-props-multiple/output.json
tests/snapshots/slots-named/output.json
tests/snapshots/typed-props/output.json
tests/snapshots/typed-slots/output.json
tests/snapshots/typedef/output.json
tests/snapshots/typedefs/output.json
tests/writer-ts-definitions.test.ts

Addresses #21
**Fixes**
- fix(component-parser): function declarations should be typed as accessors, not props

fix(component-parser): function declarations should be typed as accessors, not props

---

src/writer/writer-ts-definitions.ts
tests/writer-ts-definitions.test.ts

**Fixes**
- fix(writer): omit `moduleName` if value is "default" in generated TypeScript class export

fix(writer): omit moduleName if value is "default"

---

src/rollup-plugin.ts
src/writer/writer-ts-definitions.ts
tests/snapshots/function-declaration/output.d.ts
tests/snapshots/infer-basic/output.d.ts
tests/snapshots/infer-with-types/output.d.ts
tests/writer-ts-definitions.test.ts

**Fixes**
- write constant props as accessors in the `SvelteComponentTyped` interface

fix: write constant props as accessors in SvelteComponentTyped

---

src/rollup-plugin.ts

In case this is run on Windows, (`path.sep` will be a backslash), this will now replace those backslashes with slashes for e.g. `types/index.d.ts`.
Without this PR, running `npm run test:integration` will generate an invalid `types/index.d.ts`. With this PR, this will be fixed.

Fix backslashes in js export (#38)

---

integration/carbon/types/FileUploader/FileUploader.d.ts
integration/carbon/types/ListBox/ListBoxField.d.ts
integration/carbon/types/ListBox/ListBoxMenuIcon.d.ts
integration/carbon/types/ListBox/ListBoxSelection.d.ts
integration/carbon/types/NumberInput/NumberInput.d.ts
integration/multi-export-typed-ts-only/types/secondary-button/secondary-button.d.ts
integration/multi-export-typed/types/SecondaryButton.d.ts
integration/multi-export/types/Button.d.ts
src/writer/writer-ts-definitions.ts
tests/snapshots/function-declaration/output.d.ts
tests/snapshots/infer-basic/output.d.ts
tests/snapshots/infer-with-types/output.d.ts
tests/writer-ts-definitions.test.ts

#21
**Features**
- omit `@constant`, `@default` notations for component accessors

Omit `@constant`, `@default` notations for component accessors

---

package.json
src/ComponentParser.ts
tests/snapshots/dispatched-events-dynamic/input.svelte
tests/snapshots/dispatched-events-typed/input.svelte
tests/snapshots/dispatched-events/input.svelte
tests/snapshots/function-declaration/input.svelte
tests/snapshots/infer-basic/input.svelte
tests/snapshots/infer-with-types/input.svelte
tests/snapshots/rest-props-multiple/input.svelte
tests/snapshots/slots-spread-typed/input.svelte
tests/snapshots/slots-spread-typed/output.d.ts
tests/snapshots/slots-spread-typed/output.json
tests/snapshots/slots-spread/input.svelte
tests/snapshots/slots-spread/output.d.ts
tests/snapshots/slots-spread/output.json
yarn.lock

#45 
**Fixes**
- tolerate slot spread syntax (`<slot {...props} />`) when parsing Svelte components
Note: this is a hot fix will not attempt to infer the type of the spread attributes. Add a JSDoc notation if spreading an object to a slot:
```svelte
<script>
/** @slot {{ a: number; }} */
const props = {
a: 4,
};
</script>
<slot {...props} />
```

fix(component-parser): parse slot spread type

---

integration/carbon/COMPONENT_API.json
integration/carbon/src/Accordion/Accordion.svelte
integration/carbon/src/Accordion/AccordionItem.svelte
integration/carbon/types/Accordion/Accordion.svelte.d.ts
integration/carbon/types/Accordion/AccordionItem.svelte.d.ts
src/ComponentParser.ts
src/writer/writer-ts-definitions.ts
tests/snapshots/component-comment-multi/input.svelte
tests/snapshots/component-comment-multi/output.d.ts
tests/snapshots/component-comment-multi/output.json
tests/snapshots/component-comment-single/input.svelte
tests/snapshots/component-comment-single/output.d.ts
tests/snapshots/component-comment-single/output.json
tests/writer-ts-definitions.test.ts

#54 
This PR adds the ability to parse `` comments and add them to the generated TypeScript definition.
**Single-line comment**
Input:
```svelte
<button {...$$restProps} {type} class:primary on:click>
<slot>Click me</slot>
</button>
```
Output:
```ts
// ...
/** A button component */
export default class Button extends SvelteComponentTyped<
ButtonProps,
{ click: WindowEventMap["click"] },
{ default: {} }
> {}
```
**Multi-line comment**
Input:
```svelte
<button {...$$restProps} {type} class:primary on:click>
<slot>Click me</slot>
</button>
```
Output:
```ts
// ...
/**
* @example
* <Button>
*   <slot />
* </Button>
*/
export default class Button extends SvelteComponentTyped<
ButtonProps,
{ click: WindowEventMap["click"] },
{ default: {} }
> {}
```

Support `@component` comments

---

CHANGELOG.md
src/ComponentParser.ts
tests/snapshots/renamed-props/input.svelte
tests/snapshots/renamed-props/output.d.ts
tests/snapshots/renamed-props/output.json

This PR adds support for renamed exports such as `export { className as class }` to be detected as props and added to the generated interface. This is done by storing a list of variable declarations encountered and then looking it up when a rename export is met.
Known limitations:
- The variable declaration must appear before the `export` statement in the source code.
- The leading comment of the `export` statement is parsed, while that of the declaration is ignored.
Resolves #50

Support detecting renamed exports as props

---

README.md
src/get-svelte-entry.ts
src/index.ts
src/sveld.ts

Closes #65 
Future work:
- allow the `input` to be passed as an option (currently, it will still use `package.json#svelte`
```js
const { sveld } = require("sveld");
const pkg = require("./package.json");
sveld({
glob: true,
markdown: true,
markdownOptions: {
onAppend: (type, document, components) => {
if (type === "h1")
document.append("quote", `${components.size} components exported from ${pkg.name}@${pkg.version}.`);
},
},
json: true,
jsonOptions: {
outFile: "docs/src/COMPONENT_API.json",
},
});
```

feat: export `sveld` for programmatic usage

---

README.md

Add documentation changes to customize the output directory of type definitions generated by sveld

Docs: Customize  output directory of sveld

---

.github/workflows/ci.yml
src/writer/writer-ts-definitions.ts
tests/snapshots/mixed-events/input.svelte
tests/snapshots/mixed-events/output.d.ts
tests/snapshots/mixed-events/output.json

Currently, generated TS definitions for `@event` always wrap the type in a `CustomEvent`.
This prevents the consumer from specifying a mixed type in the case of a forwarded/dispatched event.
```svelte
<script>
/**
* @event {FocusEvent | CustomEvent<FocusEvent>} blur
*/
import { createEventDispatcher } from "svelte";
const dispatcher = createEventDispatcher();
</script>
<button
on:blur
on:blur={(e) => {
dispatcher("blur", e);
}}
/>
```
The current output is:
```ts
CustomEvent<FocusEvent | CustomEvent<FocusEvent>>
```
The expected output should be:
```ts
FocusEvent | CustomEvent<FocusEvent>
```

fix(ts): do not wrap `@event` detail in `CustomEvent` if type contains `CustomEvent`

---

integration/carbon/COMPONENT_API.json
integration/carbon/src/Link/Link.svelte
integration/carbon/types/Button/Button.svelte.d.ts
integration/carbon/types/Button/ButtonSkeleton.svelte.d.ts
integration/carbon/types/Link/Link.svelte.d.ts
integration/carbon/types/Tile/ClickableTile.svelte.d.ts
integration/carbon/types/UIShell/GlobalHeader/Header.svelte.d.ts
integration/carbon/types/UIShell/GlobalHeader/HeaderActionLink.svelte.d.ts
integration/carbon/types/UIShell/GlobalHeader/HeaderNavItem.svelte.d.ts
integration/carbon/types/UIShell/GlobalHeader/HeaderNavMenu.svelte.d.ts
integration/carbon/types/UIShell/GlobalHeader/HeaderPanelLink.svelte.d.ts
integration/carbon/types/UIShell/SideNav/SideNavLink.svelte.d.ts
integration/carbon/types/UIShell/SideNav/SideNavMenuItem.svelte.d.ts
integration/carbon/types/UIShell/SkipToContent.svelte.d.ts
integration/multi-export-typed-ts-only/types/link/link.svelte.d.ts
integration/multi-export-typed/types/Link.svelte.d.ts
integration/multi-export/types/Link.svelte.d.ts
src/writer/writer-ts-definitions.ts
tests/snapshots/anchor-props/input.svelte
tests/snapshots/anchor-props/output.d.ts
tests/snapshots/anchor-props/output.json

SvelteKit has [framework-specific attributes](https://kit.svelte.dev/docs/a-options#sveltekit-prefetch) for anchor links: `sveltekit:noscroll` and `sveltekit:prefetch`.
This PR includes those optional attributes to any component that passes `$$restProps` to an anchor element.
```tsx
/// <reference types="svelte" />
import type { SvelteComponentTyped } from "svelte";
export interface LinkProps extends svelte.JSX.HTMLAttributes<HTMLElementTagNameMap["a"]> {
/**
* SvelteKit attribute to enable data prefetching
* if a link is hovered over or touched on mobile.
* @see https://kit.svelte.dev/docs/a-options#sveltekit-prefetch
* @default false
*/
"sveltekit:prefetch"?: boolean;
/**
* SvelteKit attribute to prevent scrolling
* after the link is clicked.
* @see …
```

feat(ts): add `sveltekit:prefetch`, `sveltekit:noscroll` attributes to `$$restProps` that extend `a` elements

---

integration/carbon/types/Icon/Icon.svelte.d.ts
src/writer/writer-ts-definitions.ts
tests/snapshots/svg-props/input.svelte
tests/snapshots/svg-props/output.d.ts
tests/snapshots/svg-props/output.json

Currently, `$$restProps` passed to `svg` will generate `Props extends svelte.JSX.HTMLAttributes<HTMLElementTagNameMap["svg"]>`.
This is incorrect, as no "svg" element exists in the `HTMLElementTagNameMap` interface of `lib.dom.d.ts`.
The correct interface to extend is `svelte.JSX.SVGAttributes<SVGSVGElement>`.

fix(ts): svg `$$restProps` should extend the correct attributes

---

.gitignore
README.md
src/writer/writer-json.ts
tsconfig.json

Currently JSON schemas representing Svelte components are stored into the component's folder with a predefined name.
This feature add the possibility to export those JSON files into a specified folder and to name each one by the name of the component they belong to.
To activate this feature, a new property has been added to the `WriteJsonOptions` interface: `outDir`.
By setting a proper value for `outDir`, all JSON schemas will be stored into this folder.

Feature: export json files into specified outDir folder

---

src/writer/writer-ts-definitions.ts
tests/snapshots/anchor-props/output.d.ts

[`sveltekit:reload`](https://kit.svelte.dev/docs/a-options#sveltekit-reload) was recently added to SvelteKit.
This adds an optional `sveltekit:reload` prop and fixes a typo in the `sveltekit:noscroll` prop.

feat(ts): add `sveltekit:reload` attribute to anchor links

---

integration/carbon/COMPONENT_API.json
integration/carbon/COMPONENT_INDEX.md
integration/carbon/types/ComposedModal/ComposedModal.svelte.d.ts
integration/carbon/types/InlineLoading/InlineLoading.svelte.d.ts
integration/carbon/types/Modal/Modal.svelte.d.ts
integration/carbon/types/Search/Search.svelte.d.ts
integration/carbon/types/Tag/Tag.svelte.d.ts
integration/carbon/types/UIShell/GlobalHeader/HeaderAction.svelte.d.ts
integration/carbon/types/UIShell/GlobalHeader/HeaderActionSearch.svelte.d.ts
src/ComponentParser.ts
tests/snapshots/dispatched-events-typed/output.d.ts
tests/snapshots/dispatched-events-typed/output.json
tests/snapshots/dispatched-events/output.d.ts
tests/snapshots/dispatched-events/output.json

Currently, a dispatched event without a second argument will produce the type `CustomEvent<any>`.
```js
dispatch("event");
```
It can be more specific; the actual type is `null`.
```diff
- event: CustomEvent<any>;
+ event: CustomEvent<null>;
```

fix(component-parser): dispatched event type without detail should default to `null`

---

integration/carbon/COMPONENT_API.json
integration/carbon/COMPONENT_INDEX.md
integration/carbon/types/Button/Button.svelte.d.ts
integration/carbon/types/Button/ButtonSkeleton.svelte.d.ts
integration/carbon/types/Search/Search.svelte.d.ts
integration/carbon/types/Search/SearchSkeleton.svelte.d.ts
integration/carbon/types/TimePicker/TimePickerSelect.svelte.d.ts
integration/carbon/types/UIShell/GlobalHeader/HeaderNav.svelte.d.ts
src/ComponentParser.ts
tests/snapshots/prop-comments/input.svelte
tests/snapshots/prop-comments/output.d.ts
tests/snapshots/prop-comments/output.json

Currently, valid JSDoc tags like `@see` in prop comments are not included in the emitted TypeScript definitions.
This fixes the logic to include such tags.
**Input**
```js
/**
* This is a comment.
* @see https://github.com/
* @deprecated this prop will be removed in the next major release.
* @type {boolean | string}
*/
export let prop = true;
```
**Output**
```ts
export interface InputProps {
/**
* This is a comment.
* @see https://github.com/
* @deprecated this prop will be removed in the next major release.
* @default true
*/
prop?: boolean | string;
}
```

fix(component-parser): preserve JSDoc tags in prop comments

---

.gitignore
src/parse-exports.ts
src/rollup-plugin.ts

In current main, if your entrypoint looks something like:
```js
export { default as MyComponent } from './MyComponent.svelte';
export { default as AnotherComponent } from './AnotherComponent.svelte';
export * from './more-components';
export * from './other-components';
```
`more-components/index.js`
```js
export { default as UtilComponent } from './UtilComponent.svelte';
```
`other-components/index.js`
```js
export { default as AwesomeComponent } from './AwesomeComponent.svelte';
export * from './another-nested-components-dir';
```
`another-nested-components-dir/index.js`
```js
export { default as CoolComponent } from './CoolComponent.svelte';
```
Will only generate types for `MyComponent` and `AnotherComponent`, but with this PR it parses the export * statements and will generate …

feat: Support Export all for component parsing in svelte entrypoint

---

README.md
integration/carbon/COMPONENT_API.json
integration/carbon/COMPONENT_INDEX.md
integration/carbon/types/Dropdown/Dropdown.svelte.d.ts
src/ComponentParser.ts
tests/snapshots/bind-this-multiple/output.d.ts
tests/snapshots/bind-this-multiple/output.json
tests/snapshots/bind-this/output.d.ts
tests/snapshots/bind-this/output.json
tests/snapshots/function-declaration/output.json
tests/snapshots/infer-basic/output.d.ts
tests/snapshots/infer-basic/output.json
tests/snapshots/infer-with-types/output.d.ts
tests/snapshots/infer-with-types/output.json
tests/snapshots/required/input.svelte
tests/snapshots/required/output.d.ts
tests/snapshots/required/output.json
tests/snapshots/typed-props/output.d.ts
tests/snapshots/typed-props/output.json

Fixes #22 
#89 added a `@required` tag to denote a prop as optional. As pointed out in this [comment](https://github.com/carbon-design-system/sveld/issues/22#issuecomment-1133483095), this is not the correct approach.
Any exported `let` prop that is uninitialized is required. This can be inferred from the AST.
As a result, `@required` is not needed. It can even be misleading.
```svelte
<script>
// required prop
export let prop1;
</script>
```

breaking: required props should be inferred, remove `@required` tag

---

src/ComponentParser.ts

**Code**
```svelte
<script>
export {}
</script>
```
**AST**
```json5
// ...
{
type: "ExportNamedDeclaration";
start: 10;
end: 19;
loc: {
// ...
}
declaration: null;
specifiers: [];
source: null;
}
// ...
```
**Parse error**
```
TypeError: null is not an object (evaluating 'f.declaration.declarations')
```
---
Typescript compiled
```ts
export type A = string
```
to
```js
export {};
```

fix: handle `export {}`

---

README.md
integration/carbon/COMPONENT_API.json
integration/carbon/COMPONENT_INDEX.md
integration/carbon/src/Checkbox/Checkbox.svelte
integration/carbon/src/ContentSwitcher/ContentSwitcher.svelte
integration/carbon/test/Accordion.svelte
integration/carbon/types/Checkbox/Checkbox.svelte.d.ts
integration/carbon/types/ContentSwitcher/ContentSwitcher.svelte.d.ts
src/ComponentParser.ts
src/writer/writer-ts-definitions.ts
tests/snapshots/dispatched-events-typed/input.svelte
tests/snapshots/dispatched-events-typed/output.json

Add the ability to add a description for `@event` tags.
Signature:
```js
/**
* @event {EventDetail} eventname [event description]
*/
```

feat(event): support description for `@event` tag

---

README.md
integration/carbon/COMPONENT_API.json
integration/carbon/src/DataTable/DataTable.svelte
integration/carbon/test/Accordion.svelte
integration/carbon/types/DataTable/DataTable.svelte.d.ts
src/ComponentParser.ts
src/writer/writer-ts-definitions.ts
tests/snapshots/typed-slots/input.svelte
tests/snapshots/typed-slots/output.d.ts
tests/snapshots/typed-slots/output.json

Similar to #99, this adds the ability to add a description for `@slot` tags.
One limitation is that the default slot cannot have a description because its name must be omitted (a slot can be named "default").
Signature:
```js
/**
* @slot {Type} slot-name [slot description]
*/
```

feat(slot): support `@slot` tag descriptions

---

src/rollup-plugin.ts
src/writer/writer-markdown.ts

If no custom `markdownOptions.outFile` is specified, the fully resolved path to the default file is printed.
For consistency, only the raw `outFile` should be printed out.
```sh
- created "<user>/<folder>/COMPONENT_INDEX.md".
+ created "COMPONENT_INDEX.md".
```

fix(writer): only print `outFile` name instead of resolved path

---

playground/src/App.svelte

This is a regression.
Changing the value in the "Svelte code" dropdown does not update the value in the CodeMirror component.

chore(playground): fix dropdown reactivity

---

package.json
tests/Writer.test.ts
tests/__snapshots__/writer-ts-definitions.test.ts.snap
tests/create-exports.test.ts
tests/index.test.ts
tests/test-snapshot.js
yarn.lock

Upgrades `vitest`, along with replacing usage of `toMatchInlineSnapshot` with `toEqual`.

test: upgrade `vitest`

---

package.json
tests/Writer.test.ts
tests/WriterMarkdown.test.ts
tests/create-exports.test.ts
tests/element-tag-map.test.ts
tests/fixtures.test.ts
tests/parse-exports.test.ts
tests/writer-ts-definitions.test.ts
tsconfig.build.json
tsconfig.json
vite.config.ts

Using globals means that direct `vitest` imports can be removed.

test: use `vitest` globals

---

playground/package.json
playground/vite.config.js
playground/yarn.lock

Applying the `optimizeCss` plugin from `carbon-preprocess-svelte` can help optimize usage of pre-compiled Carbon CSS.
```sh
Optimized assets/index-Dy43zAwI.css
Before: 750.82 kB
After:  336.35 kB (-55.2%)
Optimized assets/CodeHighlighter-1BpQ5oIG.css
Before: 2.3 kB
After:  2.3 kB (-0%)
```
---

perf(playground): apply `optimizeCss` to remove unused styles

---

tests/e2e/carbon/COMPONENT_API.json
tests/e2e/carbon/COMPONENT_INDEX.md
tests/e2e/carbon/types/DataTable/DataTable.svelte.d.ts
tests/test-e2e.ts

The script that executes the `e2e` tests can be refactored to use Shell instead of Glob.
```sh
find tests/e2e -maxdepth 1
tests/e2e
tests/e2e/single-export
tests/e2e/multi-export-typed
tests/e2e/carbon
tests/e2e/multi-export
tests/e2e/multi-folders
tests/e2e/single-export-default-only
tests/e2e/glob
tests/e2e/multi-export-typed-ts-only
```

refactor(tests): use `find` instead of Glob API

---

tests/__snapshots__/fixtures.test.ts.snap
tests/fixtures/generics-multiple/input.svelte
tests/fixtures/generics-multiple/output.d.ts
tests/fixtures/generics-multiple/output.json

Avoid the "required param after optional param" error by fixing the example.

test(fixtures): fix `generics-multiple` example

---

src/writer/writer-ts-definitions.ts
tests/__snapshots__/fixtures.test.ts.snap
tests/fixtures/input-events/output.d.ts

Fixes #139 
#92 added a workaround to map cut/copy/paste events as they previously did not exist on `WindowEventMap`.
Now that these are mapped in the `WindowEventMap` interface in TypeScript `lib.dom.d.ts` definitions, fix this to avoid TS errors.

fix(writer): use `WindowEventMap` for cut/copy/paste events

---

.github/workflows/ci.yml

Any changes in `playground/**` are independent (downstream) of checks in the CI workflow and can be ignored.

ci: use `paths-ignore` in ci.yml

---

tsconfig.fixtures.json

Currently, only type declaration files inside `tests/fixtures` are type checked.
There are a couple of `.ts` files that asserts type definitions that should also be tested.

test(fixtures): ensure `.ts` are type checked

---

playground/index.html
playground/src/App.svelte
playground/src/CodeEditor.svelte
playground/src/CodeHighlighter.svelte
playground/src/Header.svelte
playground/src/TabContentOverlay.svelte
playground/src/TabJson.svelte
playground/src/TabMarkdown.svelte
playground/src/TabTypeScript.svelte
playground/src/data.js
playground/src/index.js

The cursor in the codemirror instance is resetting on type.
The fix is to imperatively call `setValue` on `codemirror` when the file selection changes. Otherwise, `setValue` is called whenever `value` changes.

chore(playground): fix cursor resetting in codemirror

---

tests/__snapshots__/fixtures.test.ts.snap

Expected fix – Bun 1.1.37 fixes [template literal escaping](https://bun.sh/blog/bun-v1.1.37#fixed-quote-and-template-escaping-in-expect-tomatchsnapshot) in snapshots.

test(fixtures): update snapshots
